### ISSUE TITLE
Justify content start

### ISSUE THREAD

**Issue by millerraycell** [frotaluiza/Projeto-Final-Angular-Let-s-Code#7]
@frotaluiza 

No arquivo [SCSS Landing page](https://github.com/frotaluiza/Projeto-Final-Angular-Let-s-Code/blob/master/src/app/Components/landing-page/landing-page.component.scss), linha **162**, o código apresenta 
```css
#flexList{
    display:flex;
    max-width: 1000px;
    color: rgb(117, 117, 117);
    justify-content: start;
    flex-wrap: wrap;
    min-width: 200px;
}
```

e está apresentando warning no justify-content, o recomendado pelo angular é
```css
#flexList{
    display:flex;
    max-width: 1000px;
    color: rgb(117, 117, 117);
    justify-content: flex-start;
    flex-wrap: wrap;
    min-width: 200px;
}
```

Como não sabia o propósito exato desse start preferi não mexer, quando puder, da uma olhada por favor.
